name: Create and Deploy Bootable Image

on:
  push:
    branches:
      - main

jobs:
  build_image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Packer
        uses: hashicorp/setup-packer@v1

      - name: Build Bootable Image
        run: |
          packer build packer.json

  deploy_image:
    runs-on: ubuntu-latest

    needs: build_image

    steps:
      - name: Upload Bootable Image
        uses: actions/upload-artifact@v2
        with:
          name: bootable-image
          path: output_directory/*.qcow2
